Syntax 6

SectionUseCase."HiFi" {
        File "HiFi.conf"
        Comment "High Fidelity Audio"
}

SectionDefaults [
        cdev "hw:${CardId}"
        cset "name='FM Transmitter Switch' Off"
        cset "name='Speaker Function' Off"
        cset "name='Jack Function' Off"
        cset "name='Earphone Switch' off"
        cset "name='FM Transmitter Switch' off"
        cset "name='PCM Playback Volume' 127,127"
]
