# This is required for plymouth to show any splash:
splash

# If plymouth detects *any* serial console, it disables the splash, even if
# there's a valid drm-enabled console available. This tells plymouth to run
# anyways.
plymouth.ignore-serial-consoles
