# This is required for plymouth to show any splash:
splash

# If plymouth detects *any* serial console, it disables the splash, even if
# there's a valid drm-enabled console available. This tells plymouth to run
# anyways.
plymouth.ignore-serial-consoles

# Newer releases of plymouth include a new standalone console viewer to replace
# fbcon in kernels with CONFIG_VT disabled. However it is quite slow, needs
# an additional monospace font, and we have no plans to disable CONFIG_VT
# anytime soon. Tell plymouth to prefer the old way of using fbcon for logging.
plymouth.prefer-fbcon
