# Needed to prevent GDM from running gnome initial setup.
# FIXME: This (g-i-s) conflicts with our first boot config, at some point we
# should make our thing not run in favor of using g-i-s on GNOME installs,
# but g-i-s wasn't super reliable and is apparently being replaced
# https://gitlab.gnome.org/Teams/STF/setup
gnome.initial-setup=0
