# systemd considers /run/lock a legacy path, with its tmpfiles config locked
# behind enabling sysv compat, which we don't want. Thus, create the path in
# a custom distro config for alsa-utils, which needs it

d /run/lock 0755 root root -
