[connection-wwan]
match-device=type:gsm
ipv4.route-table=1430
ipv6.route-table=1430

# Disable per-device connectivity checks on cellular, because:
# - (assumed to be) no captive portals on GSM
# - +20000 route penalty shouldn't have any impact with other config above (e.g.
#   route # table 1430)
# This is needed to fix a small leak (1KB/10min) where traffic is still sent
# over wwan when e.g. connected to wifi
[device-wwan]
match-device=type:gsm;type:rmnet
check-connectivity=no
