# systemd-gpt-auto-generator does not set JobTimeoutSec=infinity on
# dev-gpt-auto-root.device, so if the user takes longer than
# DefaultDeviceTimeoutSec (90s) to enter their LUKS passphrase, the device
# unit times out and the system falls into the emergency shell.
# Workaround for: https://github.com/systemd/systemd/issues/35870
[Unit]
JobTimeoutSec=infinity
