[intro]
title=Welcome to postmarketOS!
body=The next few screens will assist you with setting up your device.

[form.username]
type=text
label=Please enter a new username
required=true

[form.password]
type=password
label=Set a password for the account
required=true

[form.fde_passphrase]
type=password
label=Set a passphrase for disk encryption (optional)
required=false
