monitor.alsa.rules = [
  {
    matches = [
      {
        # Matches all sinks of the internal sound card
        node.name = "~alsa_output.*"
        alsa.card_name = "Fairphone 5"
      }
    ]
    actions = {
      update-props = {
        audio.format           = "S32LE"
     }
    }
  }
]
