[Unit]
After=default.target modprobe@libcomposite.service sys-kernel-config.mount
Requires=modprobe@libcomposite.service sys-kernel-config.mount

[Service]
ExecStartPre=-/bin/sh -c 'killall unudhcpd 2>/dev/null'
ExecStartPre=mkdir -p /sys/kernel/config/usb_gadget/g1/configs/c.1
