Syntax 3

SectionUseCase."HiFi" {
	File "/Google/taimen/HiFi.conf"
	Comment "Loudspeakers and the built-in microphone"
}

SectionUseCase."Voice Call" {
	File "/Google/taimen/VoiceCall.conf"
	Comment "Voice call"
}
